language: node_js
node_js:
- 9
- 8
matrix:
  allow_failures:
  - node_js: 9
branches:
  only:
  - master
  - "/^v\\d.*$/"
deploy:
  provider: npm
  email: baderbuddy@gmail.com
  api_key:
    secure: Z3YyEhthROWCdnvaNTW7n/ELbvBp+MIw+fWQ9Tt12TVuhVKENJJlhhPWQr92Dv03t3P0NVYMhr+ai5HQgPsnc+lGuEK6bj355KShC9V9W5+YPpUhHRrbW+l8/qWTMTCIfH3I0wrzjSJ9T+c8p0J0/Ay/5Fy+77uX/j+JzXiPclw=
  on:
    tags: true
    repo: deepsweet/mustache-loader
